apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-fdobmhrc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/go-fdobmhrc:azure-0f64320784908300fc465960ae5a89f816d3d1ac
          name: container-image
